language: python
python:
- '3.6'
matrix:
  fast_finish: true

before_deploy:
  - git config --local user.name JulienHivert
  - git config --local user.email julienhivert.tt@gmail.com
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  skip_cleanup: true
  provider: releases
  script: "./face_detection.py"
  on:
    branch: master
env:
  global:
    secure: KNZDwCMas4yoUvwIvMF/4ZyexBF9CgidJBM6HHFEyZR0A+M9Vhni0rg8BGqiyvZQtmW2WYarW6t86svwhH/D0kpCxjwvbIsLtfGt9zGH0k+xv8zcaTEWuuRM7GSBxeqdX+l4elEm2ZDXSsM5iz8xRZoqP1+Jg0V7mFI+CDtS+nXYoNvKMQGDm53hAS2Q8/8syGWr0GueWpzUClEkFbBgDFJ0+0z9SaixtH0KMPWtGMf2ygX0xdi3gGSIx+KVnVlm/7w+YupyOVfrcSxvyM+KESOHCmS/jK2iJkVX/S+t9ft7u0LVcTnuARNKaATRpfu1G75GyoTjMCnwJUxpB+eL6HN4g4g06MtbTxAYB1YBSzbCipIF3wBP8jX+arD1b8W7waLw43VuN0ljerHNhNPseUsC+OVifAZ0LAmEDP7rkc9O3xAldhKgrTWihzojOHJK7RjUl2fG5+mfeytly0+2MZOiIUIRlmKROgCW7D2o3ok9N+Hpxt6jMPPGg0HaWvyrEDz7SpLzI37THvzJXRqVi/HOUKVFQTWHIyaH/M0+CJeeg4Thug4DStfHTwMC2xFAp+fMKaU6CXVnsGPb6X77n07S/hXk7py/mxedfwCScWSfcJDvBYD91e1sn5G/f1TPB6qg4J7OSFopwvybKmGKEJVKks09I4bRvMvSNBq3FeU=
    GIT_DEPLOY_REPO=https://a83810dcc1a3fea8e0b0e18d968e4588156487c7@github.com/JulienHivert/FaceDetection_MagicMirror